name: ci

on:
  - push

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: gem Install Prettier
        run: |
          gem install prettier

      - name: gem Install Htmlbeautifier
        run: |
          gem install htmlbeautifier

      - name: npm Install Prettier
        run: |
          npm install -g prettier

      - name: Install Prettier Plugin
        run: |
          npm install --save-dev prettier @prettier/plugin-ruby

      - name: Run Prettier & Htmlbeautifier
        run: |
          ./node_modules/.bin/prettier --write '**/*.rb'
          prettier --write '**/*.{css,html,js}'
          htmlbeautifier '**/*.erb'


      - name: Commit format
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Format